name: autowrite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python and Poetry
        uses: snok/install-poetry@v1
        with:
          python-version: 3.12
          # Optional: ask poetry to create the virtualenv in the project directory
          virtualenvs-in-project: true
          # Optional: cache the dependencies using GitHub's cache
          cache: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      
      - name: Run tests
        run: poetry run pytest
